# -*- coding: utf-8 -*-
"""DataScience1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UxKNTeCTck7ylsE-l-dl_bC9gB4_Jcup
"""

import re
#inp = ["hello", "hi", "helo"]
inp = []
n = int(input('Enter number of words :'))

for i in range(n):
  inp.append(input('Enter the next word :'))
txt = input('Enter the target word :')
count=0
reg=""
for i in inp:
    x = re.findall(r"((\w)\2*)", i)
    reg = "^"
    for j in x:
        reg += "("+j[1]+"{3,}|"+j[0]+")"
    reg += "$"
    if(re.search(reg,txt)):
        count +=1
print(count)